# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AzureKeyVault(Model):
    """AzureKeyVault.

    :param vault_id:
    :type vault_id: str
    :param vault_name:
    :type vault_name: str
    :param vault_url:
    :type vault_url: str
    """

    _attribute_map = {
        'vault_id': {'key': 'vaultId', 'type': 'str'},
        'vault_name': {'key': 'vaultName', 'type': 'str'},
        'vault_url': {'key': 'vaultUrl', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(AzureKeyVault, self).__init__(**kwargs)
        self.vault_id = kwargs.get('vault_id', None)
        self.vault_name = kwargs.get('vault_name', None)
        self.vault_url = kwargs.get('vault_url', None)
