# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ProjectDefinition(Model):
    """ProjectDefinition.

    :param name:
    :type name: str
    :param project_type:
    :type project_type: str
    :param users:
    :type users: list[~teamcloud.models.UserDefinition]
    :param tags:
    :type tags: dict[str, str]
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'project_type': {'key': 'projectType', 'type': 'str'},
        'users': {'key': 'users', 'type': '[UserDefinition]'},
        'tags': {'key': 'tags', 'type': '{str}'},
    }

    def __init__(self, *, name: str=None, project_type: str=None, users=None, tags=None, **kwargs) -> None:
        super(ProjectDefinition, self).__init__(**kwargs)
        self.name = name
        self.project_type = project_type
        self.users = users
        self.tags = tags
