# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .azure_identity_py3 import AzureIdentity


class ProjectIdentity(AzureIdentity):
    """ProjectIdentity.

    :param id:
    :type id: str
    :param app_id:
    :type app_id: str
    :param secret:
    :type secret: str
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'app_id': {'key': 'appId', 'type': 'str'},
        'secret': {'key': 'secret', 'type': 'str'},
    }

    def __init__(self, *, id: str=None, app_id: str=None, secret: str=None, **kwargs) -> None:
        super(ProjectIdentity, self).__init__(id=id, app_id=app_id, secret=secret, **kwargs)
