import { OperationParameter, OperationURLParameter } from "@azure/core-http";
export declare const accept: OperationParameter;
export declare const $host: OperationURLParameter;
export declare const organizationId: OperationURLParameter;
export declare const projectId: OperationURLParameter;
export declare const contentType: OperationParameter;
export declare const body: OperationParameter;
export declare const id: OperationURLParameter;
export declare const componentId: OperationURLParameter;
export declare const body1: OperationParameter;
export declare const body2: OperationParameter;
export declare const body3: OperationParameter;
export declare const body4: OperationParameter;
export declare const org: OperationURLParameter;
export declare const body5: OperationParameter;
export declare const userId: OperationURLParameter;
export declare const body6: OperationParameter;
export declare const body7: OperationParameter;
export declare const body8: OperationParameter;
export declare const tagKey: OperationURLParameter;
export declare const body9: OperationParameter;
export declare const projectTemplateId: OperationURLParameter;
export declare const body10: OperationParameter;
export declare const trackingId: OperationURLParameter;
//# sourceMappingURL=parameters.d.ts.map