# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

import datetime
from typing import Dict, List, Optional, Union

import msrest.serialization

from ._team_cloud_client_enums import *


class AzureResourceGroup(msrest.serialization.Model):
    """AzureResourceGroup.

    All required parameters must be populated in order to send to Azure.

    :param id: Required.
    :type id: str
    :param name: Required.
    :type name: str
    :param subscription_id: Required.
    :type subscription_id: str
    :param region: Required.
    :type region: str
    """

    _validation = {
        'id': {'required': True},
        'name': {'required': True},
        'subscription_id': {'required': True},
        'region': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'subscription_id': {'key': 'subscriptionId', 'type': 'str'},
        'region': {'key': 'region', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        id: str,
        name: str,
        subscription_id: str,
        region: str,
        **kwargs
    ):
        super(AzureResourceGroup, self).__init__(**kwargs)
        self.id = id
        self.name = name
        self.subscription_id = subscription_id
        self.region = region


class Component(msrest.serialization.Model):
    """Component.

    All required parameters must be populated in order to send to Azure.

    :param id: Required.
    :type id: str
    :param href:
    :type href: str
    :param offer_id:
    :type offer_id: str
    :param project_id:
    :type project_id: str
    :param provider_id: Required.
    :type provider_id: str
    :param requested_by: Required.
    :type requested_by: str
    :param display_name:
    :type display_name: str
    :param description:
    :type description: str
    :param input_json:
    :type input_json: str
    :param value_json:
    :type value_json: str
    :param scope: Required.  Possible values include: "System", "Project", "All".
    :type scope: str or ~teamcloud.models.ComponentScope
    :param type: Required.  Possible values include: "Custom", "GitRepository".
    :type type: str or ~teamcloud.models.ComponentType
    """

    _validation = {
        'id': {'required': True},
        'provider_id': {'required': True},
        'requested_by': {'required': True},
        'scope': {'required': True},
        'type': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'href': {'key': 'href', 'type': 'str'},
        'offer_id': {'key': 'offerId', 'type': 'str'},
        'project_id': {'key': 'projectId', 'type': 'str'},
        'provider_id': {'key': 'providerId', 'type': 'str'},
        'requested_by': {'key': 'requestedBy', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'input_json': {'key': 'inputJson', 'type': 'str'},
        'value_json': {'key': 'valueJson', 'type': 'str'},
        'scope': {'key': 'scope', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        id: str,
        provider_id: str,
        requested_by: str,
        scope: Union[str, "ComponentScope"],
        type: Union[str, "ComponentType"],
        href: Optional[str] = None,
        offer_id: Optional[str] = None,
        project_id: Optional[str] = None,
        display_name: Optional[str] = None,
        description: Optional[str] = None,
        input_json: Optional[str] = None,
        value_json: Optional[str] = None,
        **kwargs
    ):
        super(Component, self).__init__(**kwargs)
        self.id = id
        self.href = href
        self.offer_id = offer_id
        self.project_id = project_id
        self.provider_id = provider_id
        self.requested_by = requested_by
        self.display_name = display_name
        self.description = description
        self.input_json = input_json
        self.value_json = value_json
        self.scope = scope
        self.type = type


class ComponentDataResult(msrest.serialization.Model):
    """ComponentDataResult.

    :param code:
    :type code: int
    :param status:
    :type status: str
    :param data:
    :type data: ~teamcloud.models.Component
    :param location:
    :type location: str
    """

    _attribute_map = {
        'code': {'key': 'code', 'type': 'int'},
        'status': {'key': 'status', 'type': 'str'},
        'data': {'key': 'data', 'type': 'Component'},
        'location': {'key': 'location', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        code: Optional[int] = None,
        status: Optional[str] = None,
        data: Optional["Component"] = None,
        location: Optional[str] = None,
        **kwargs
    ):
        super(ComponentDataResult, self).__init__(**kwargs)
        self.code = code
        self.status = status
        self.data = data
        self.location = location


class ComponentListDataResult(msrest.serialization.Model):
    """ComponentListDataResult.

    Variables are only populated by the server, and will be ignored when sending a request.

    :param code:
    :type code: int
    :param status:
    :type status: str
    :ivar data:
    :vartype data: list[~teamcloud.models.Component]
    :param location:
    :type location: str
    """

    _validation = {
        'data': {'readonly': True},
    }

    _attribute_map = {
        'code': {'key': 'code', 'type': 'int'},
        'status': {'key': 'status', 'type': 'str'},
        'data': {'key': 'data', 'type': '[Component]'},
        'location': {'key': 'location', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        code: Optional[int] = None,
        status: Optional[str] = None,
        location: Optional[str] = None,
        **kwargs
    ):
        super(ComponentListDataResult, self).__init__(**kwargs)
        self.code = code
        self.status = status
        self.data = None
        self.location = location


class ComponentOffer(msrest.serialization.Model):
    """ComponentOffer.

    All required parameters must be populated in order to send to Azure.

    :param id: Required.
    :type id: str
    :param provider_id: Required.
    :type provider_id: str
    :param display_name:
    :type display_name: str
    :param description:
    :type description: str
    :param input_json_schema:
    :type input_json_schema: str
    :param scope: Required.  Possible values include: "System", "Project", "All".
    :type scope: str or ~teamcloud.models.ComponentOfferScope
    :param type: Required.  Possible values include: "Custom", "GitRepository".
    :type type: str or ~teamcloud.models.ComponentOfferType
    """

    _validation = {
        'id': {'required': True},
        'provider_id': {'required': True},
        'scope': {'required': True},
        'type': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'provider_id': {'key': 'providerId', 'type': 'str'},
        'display_name': {'key': 'displayName', 'type': 'str'},
        'description': {'key': 'description', 'type': 'str'},
        'input_json_schema': {'key': 'inputJsonSchema', 'type': 'str'},
        'scope': {'key': 'scope', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        id: str,
        provider_id: str,
        scope: Union[str, "ComponentOfferScope"],
        type: Union[str, "ComponentOfferType"],
        display_name: Optional[str] = None,
        description: Optional[str] = None,
        input_json_schema: Optional[str] = None,
        **kwargs
    ):
        super(ComponentOffer, self).__init__(**kwargs)
        self.id = id
        self.provider_id = provider_id
        self.display_name = display_name
        self.description = description
        self.input_json_schema = input_json_schema
        self.scope = scope
        self.type = type


class ComponentOfferDataResult(msrest.serialization.Model):
    """ComponentOfferDataResult.

    :param code:
    :type code: int
    :param status:
    :type status: str
    :param data:
    :type data: ~teamcloud.models.ComponentOffer
    :param location:
    :type location: str
    """

    _attribute_map = {
        'code': {'key': 'code', 'type': 'int'},
        'status': {'key': 'status', 'type': 'str'},
        'data': {'key': 'data', 'type': 'ComponentOffer'},
        'location': {'key': 'location', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        code: Optional[int] = None,
        status: Optional[str] = None,
        data: Optional["ComponentOffer"] = None,
        location: Optional[str] = None,
        **kwargs
    ):
        super(ComponentOfferDataResult, self).__init__(**kwargs)
        self.code = code
        self.status = status
        self.data = data
        self.location = location


class ComponentOfferListDataResult(msrest.serialization.Model):
    """ComponentOfferListDataResult.

    Variables are only populated by the server, and will be ignored when sending a request.

    :param code:
    :type code: int
    :param status:
    :type status: str
    :ivar data:
    :vartype data: list[~teamcloud.models.ComponentOffer]
    :param location:
    :type location: str
    """

    _validation = {
        'data': {'readonly': True},
    }

    _attribute_map = {
        'code': {'key': 'code', 'type': 'int'},
        'status': {'key': 'status', 'type': 'str'},
        'data': {'key': 'data', 'type': '[ComponentOffer]'},
        'location': {'key': 'location', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        code: Optional[int] = None,
        status: Optional[str] = None,
        location: Optional[str] = None,
        **kwargs
    ):
        super(ComponentOfferListDataResult, self).__init__(**kwargs)
        self.code = code
        self.status = status
        self.data = None
        self.location = location


class ComponentRequest(msrest.serialization.Model):
    """ComponentRequest.

    All required parameters must be populated in order to send to Azure.

    :param offer_id: Required.
    :type offer_id: str
    :param input_json:
    :type input_json: str
    """

    _validation = {
        'offer_id': {'required': True},
    }

    _attribute_map = {
        'offer_id': {'key': 'offerId', 'type': 'str'},
        'input_json': {'key': 'inputJson', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        offer_id: str,
        input_json: Optional[str] = None,
        **kwargs
    ):
        super(ComponentRequest, self).__init__(**kwargs)
        self.offer_id = offer_id
        self.input_json = input_json


class ErrorResult(msrest.serialization.Model):
    """ErrorResult.

    :param code:
    :type code: int
    :param status:
    :type status: str
    :param errors:
    :type errors: list[~teamcloud.models.ResultError]
    """

    _attribute_map = {
        'code': {'key': 'code', 'type': 'int'},
        'status': {'key': 'status', 'type': 'str'},
        'errors': {'key': 'errors', 'type': '[ResultError]'},
    }

    def __init__(
        self,
        *,
        code: Optional[int] = None,
        status: Optional[str] = None,
        errors: Optional[List["ResultError"]] = None,
        **kwargs
    ):
        super(ErrorResult, self).__init__(**kwargs)
        self.code = code
        self.status = status
        self.errors = errors


class Project(msrest.serialization.Model):
    """Project.

    All required parameters must be populated in order to send to Azure.

    :param id: Required.
    :type id: str
    :param name: Required.
    :type name: str
    :param type: Required.
    :type type: ~teamcloud.models.ProjectType
    :param resource_group:
    :type resource_group: ~teamcloud.models.AzureResourceGroup
    :param users: Required.
    :type users: list[~teamcloud.models.User]
    :param tags: A set of tags. Dictionary of :code:`<string>`.
    :type tags: dict[str, str]
    :param properties: Dictionary of :code:`<string>`.
    :type properties: dict[str, str]
    :param links:
    :type links: ~teamcloud.models.ProjectReferenceLinks
    """

    _validation = {
        'id': {'required': True},
        'name': {'required': True},
        'type': {'required': True},
        'users': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'type': {'key': 'type', 'type': 'ProjectType'},
        'resource_group': {'key': 'resourceGroup', 'type': 'AzureResourceGroup'},
        'users': {'key': 'users', 'type': '[User]'},
        'tags': {'key': 'tags', 'type': '{str}'},
        'properties': {'key': 'properties', 'type': '{str}'},
        'links': {'key': '_links', 'type': 'ProjectReferenceLinks'},
    }

    def __init__(
        self,
        *,
        id: str,
        name: str,
        type: "ProjectType",
        users: List["User"],
        resource_group: Optional["AzureResourceGroup"] = None,
        tags: Optional[Dict[str, str]] = None,
        properties: Optional[Dict[str, str]] = None,
        links: Optional["ProjectReferenceLinks"] = None,
        **kwargs
    ):
        super(Project, self).__init__(**kwargs)
        self.id = id
        self.name = name
        self.type = type
        self.resource_group = resource_group
        self.users = users
        self.tags = tags
        self.properties = properties
        self.links = links


class ProjectDataResult(msrest.serialization.Model):
    """ProjectDataResult.

    :param code:
    :type code: int
    :param status:
    :type status: str
    :param data:
    :type data: ~teamcloud.models.Project
    :param location:
    :type location: str
    """

    _attribute_map = {
        'code': {'key': 'code', 'type': 'int'},
        'status': {'key': 'status', 'type': 'str'},
        'data': {'key': 'data', 'type': 'Project'},
        'location': {'key': 'location', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        code: Optional[int] = None,
        status: Optional[str] = None,
        data: Optional["Project"] = None,
        location: Optional[str] = None,
        **kwargs
    ):
        super(ProjectDataResult, self).__init__(**kwargs)
        self.code = code
        self.status = status
        self.data = data
        self.location = location


class ProjectDefinition(msrest.serialization.Model):
    """ProjectDefinition.

    :param name:
    :type name: str
    :param project_type:
    :type project_type: str
    :param users:
    :type users: list[~teamcloud.models.UserDefinition]
    :param tags: A set of tags. Dictionary of :code:`<string>`.
    :type tags: dict[str, str]
    :param properties: Dictionary of :code:`<string>`.
    :type properties: dict[str, str]
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'project_type': {'key': 'projectType', 'type': 'str'},
        'users': {'key': 'users', 'type': '[UserDefinition]'},
        'tags': {'key': 'tags', 'type': '{str}'},
        'properties': {'key': 'properties', 'type': '{str}'},
    }

    def __init__(
        self,
        *,
        name: Optional[str] = None,
        project_type: Optional[str] = None,
        users: Optional[List["UserDefinition"]] = None,
        tags: Optional[Dict[str, str]] = None,
        properties: Optional[Dict[str, str]] = None,
        **kwargs
    ):
        super(ProjectDefinition, self).__init__(**kwargs)
        self.name = name
        self.project_type = project_type
        self.users = users
        self.tags = tags
        self.properties = properties


class ProjectIdentity(msrest.serialization.Model):
    """ProjectIdentity.

    All required parameters must be populated in order to send to Azure.

    :param id: Required.
    :type id: str
    :param tenant_id: Required.
    :type tenant_id: str
    :param application_id: Required.
    :type application_id: str
    :param secret: Required.
    :type secret: str
    """

    _validation = {
        'id': {'required': True},
        'tenant_id': {'required': True},
        'application_id': {'required': True},
        'secret': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'tenant_id': {'key': 'tenantId', 'type': 'str'},
        'application_id': {'key': 'applicationId', 'type': 'str'},
        'secret': {'key': 'secret', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        id: str,
        tenant_id: str,
        application_id: str,
        secret: str,
        **kwargs
    ):
        super(ProjectIdentity, self).__init__(**kwargs)
        self.id = id
        self.tenant_id = tenant_id
        self.application_id = application_id
        self.secret = secret


class ProjectIdentityDataResult(msrest.serialization.Model):
    """ProjectIdentityDataResult.

    :param code:
    :type code: int
    :param status:
    :type status: str
    :param data:
    :type data: ~teamcloud.models.ProjectIdentity
    :param location:
    :type location: str
    """

    _attribute_map = {
        'code': {'key': 'code', 'type': 'int'},
        'status': {'key': 'status', 'type': 'str'},
        'data': {'key': 'data', 'type': 'ProjectIdentity'},
        'location': {'key': 'location', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        code: Optional[int] = None,
        status: Optional[str] = None,
        data: Optional["ProjectIdentity"] = None,
        location: Optional[str] = None,
        **kwargs
    ):
        super(ProjectIdentityDataResult, self).__init__(**kwargs)
        self.code = code
        self.status = status
        self.data = data
        self.location = location


class ProjectLink(msrest.serialization.Model):
    """ProjectLink.

    All required parameters must be populated in order to send to Azure.

    :param id: Required.
    :type id: str
    :param href: Required.
    :type href: str
    :param title:
    :type title: str
    :param type: Required.  Possible values include: "Link", "Readme", "Service", "GitRepository",
     "AzureResource".
    :type type: str or ~teamcloud.models.ProjectLinkType
    """

    _validation = {
        'id': {'required': True},
        'href': {'required': True},
        'type': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'href': {'key': 'href', 'type': 'str'},
        'title': {'key': 'title', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        id: str,
        href: str,
        type: Union[str, "ProjectLinkType"],
        title: Optional[str] = None,
        **kwargs
    ):
        super(ProjectLink, self).__init__(**kwargs)
        self.id = id
        self.href = href
        self.title = title
        self.type = type


class ProjectLinkDataResult(msrest.serialization.Model):
    """ProjectLinkDataResult.

    :param code:
    :type code: int
    :param status:
    :type status: str
    :param data:
    :type data: ~teamcloud.models.ProjectLink
    :param location:
    :type location: str
    """

    _attribute_map = {
        'code': {'key': 'code', 'type': 'int'},
        'status': {'key': 'status', 'type': 'str'},
        'data': {'key': 'data', 'type': 'ProjectLink'},
        'location': {'key': 'location', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        code: Optional[int] = None,
        status: Optional[str] = None,
        data: Optional["ProjectLink"] = None,
        location: Optional[str] = None,
        **kwargs
    ):
        super(ProjectLinkDataResult, self).__init__(**kwargs)
        self.code = code
        self.status = status
        self.data = data
        self.location = location


class ProjectLinkListDataResult(msrest.serialization.Model):
    """ProjectLinkListDataResult.

    Variables are only populated by the server, and will be ignored when sending a request.

    :param code:
    :type code: int
    :param status:
    :type status: str
    :ivar data:
    :vartype data: list[~teamcloud.models.ProjectLink]
    :param location:
    :type location: str
    """

    _validation = {
        'data': {'readonly': True},
    }

    _attribute_map = {
        'code': {'key': 'code', 'type': 'int'},
        'status': {'key': 'status', 'type': 'str'},
        'data': {'key': 'data', 'type': '[ProjectLink]'},
        'location': {'key': 'location', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        code: Optional[int] = None,
        status: Optional[str] = None,
        location: Optional[str] = None,
        **kwargs
    ):
        super(ProjectLinkListDataResult, self).__init__(**kwargs)
        self.code = code
        self.status = status
        self.data = None
        self.location = location


class ProjectListDataResult(msrest.serialization.Model):
    """ProjectListDataResult.

    Variables are only populated by the server, and will be ignored when sending a request.

    :param code:
    :type code: int
    :param status:
    :type status: str
    :ivar data:
    :vartype data: list[~teamcloud.models.Project]
    :param location:
    :type location: str
    """

    _validation = {
        'data': {'readonly': True},
    }

    _attribute_map = {
        'code': {'key': 'code', 'type': 'int'},
        'status': {'key': 'status', 'type': 'str'},
        'data': {'key': 'data', 'type': '[Project]'},
        'location': {'key': 'location', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        code: Optional[int] = None,
        status: Optional[str] = None,
        location: Optional[str] = None,
        **kwargs
    ):
        super(ProjectListDataResult, self).__init__(**kwargs)
        self.code = code
        self.status = status
        self.data = None
        self.location = location


class ProjectMembership(msrest.serialization.Model):
    """ProjectMembership.

    All required parameters must be populated in order to send to Azure.

    :param project_id: Required.
    :type project_id: str
    :param role: Required.  Possible values include: "None", "Provider", "Member", "Owner".
    :type role: str or ~teamcloud.models.ProjectMembershipRole
    :param properties: Dictionary of :code:`<string>`.
    :type properties: dict[str, str]
    """

    _validation = {
        'project_id': {'required': True},
        'role': {'required': True},
    }

    _attribute_map = {
        'project_id': {'key': 'projectId', 'type': 'str'},
        'role': {'key': 'role', 'type': 'str'},
        'properties': {'key': 'properties', 'type': '{str}'},
    }

    def __init__(
        self,
        *,
        project_id: str,
        role: Union[str, "ProjectMembershipRole"],
        properties: Optional[Dict[str, str]] = None,
        **kwargs
    ):
        super(ProjectMembership, self).__init__(**kwargs)
        self.project_id = project_id
        self.role = role
        self.properties = properties


class ProjectReferenceLinks(msrest.serialization.Model):
    """ProjectReferenceLinks.

    :param self_property:
    :type self_property: ~teamcloud.models.ReferenceLink
    :param identity:
    :type identity: ~teamcloud.models.ReferenceLink
    :param users:
    :type users: ~teamcloud.models.ReferenceLink
    :param links:
    :type links: ~teamcloud.models.ReferenceLink
    :param offers:
    :type offers: ~teamcloud.models.ReferenceLink
    :param components:
    :type components: ~teamcloud.models.ReferenceLink
    """

    _attribute_map = {
        'self_property': {'key': '_self', 'type': 'ReferenceLink'},
        'identity': {'key': 'identity', 'type': 'ReferenceLink'},
        'users': {'key': 'users', 'type': 'ReferenceLink'},
        'links': {'key': 'links', 'type': 'ReferenceLink'},
        'offers': {'key': 'offers', 'type': 'ReferenceLink'},
        'components': {'key': 'components', 'type': 'ReferenceLink'},
    }

    def __init__(
        self,
        *,
        self_property: Optional["ReferenceLink"] = None,
        identity: Optional["ReferenceLink"] = None,
        users: Optional["ReferenceLink"] = None,
        links: Optional["ReferenceLink"] = None,
        offers: Optional["ReferenceLink"] = None,
        components: Optional["ReferenceLink"] = None,
        **kwargs
    ):
        super(ProjectReferenceLinks, self).__init__(**kwargs)
        self.self_property = self_property
        self.identity = identity
        self.users = users
        self.links = links
        self.offers = offers
        self.components = components


class ProjectType(msrest.serialization.Model):
    """ProjectType.

    All required parameters must be populated in order to send to Azure.

    :param id: Required.
    :type id: str
    :param is_default:
    :type is_default: bool
    :param region: Required.
    :type region: str
    :param subscriptions: Required.
    :type subscriptions: list[str]
    :param subscription_capacity:
    :type subscription_capacity: int
    :param resource_group_name_prefix:
    :type resource_group_name_prefix: str
    :param providers: Required.
    :type providers: list[~teamcloud.models.ProviderReference]
    :param tags: A set of tags. Dictionary of :code:`<string>`.
    :type tags: dict[str, str]
    :param properties: Dictionary of :code:`<string>`.
    :type properties: dict[str, str]
    """

    _validation = {
        'id': {'required': True},
        'region': {'required': True},
        'subscriptions': {'required': True},
        'providers': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'is_default': {'key': 'isDefault', 'type': 'bool'},
        'region': {'key': 'region', 'type': 'str'},
        'subscriptions': {'key': 'subscriptions', 'type': '[str]'},
        'subscription_capacity': {'key': 'subscriptionCapacity', 'type': 'int'},
        'resource_group_name_prefix': {'key': 'resourceGroupNamePrefix', 'type': 'str'},
        'providers': {'key': 'providers', 'type': '[ProviderReference]'},
        'tags': {'key': 'tags', 'type': '{str}'},
        'properties': {'key': 'properties', 'type': '{str}'},
    }

    def __init__(
        self,
        *,
        id: str,
        region: str,
        subscriptions: List[str],
        providers: List["ProviderReference"],
        is_default: Optional[bool] = None,
        subscription_capacity: Optional[int] = None,
        resource_group_name_prefix: Optional[str] = None,
        tags: Optional[Dict[str, str]] = None,
        properties: Optional[Dict[str, str]] = None,
        **kwargs
    ):
        super(ProjectType, self).__init__(**kwargs)
        self.id = id
        self.is_default = is_default
        self.region = region
        self.subscriptions = subscriptions
        self.subscription_capacity = subscription_capacity
        self.resource_group_name_prefix = resource_group_name_prefix
        self.providers = providers
        self.tags = tags
        self.properties = properties


class ProjectTypeDataResult(msrest.serialization.Model):
    """ProjectTypeDataResult.

    :param code:
    :type code: int
    :param status:
    :type status: str
    :param data:
    :type data: ~teamcloud.models.ProjectType
    :param location:
    :type location: str
    """

    _attribute_map = {
        'code': {'key': 'code', 'type': 'int'},
        'status': {'key': 'status', 'type': 'str'},
        'data': {'key': 'data', 'type': 'ProjectType'},
        'location': {'key': 'location', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        code: Optional[int] = None,
        status: Optional[str] = None,
        data: Optional["ProjectType"] = None,
        location: Optional[str] = None,
        **kwargs
    ):
        super(ProjectTypeDataResult, self).__init__(**kwargs)
        self.code = code
        self.status = status
        self.data = data
        self.location = location


class ProjectTypeListDataResult(msrest.serialization.Model):
    """ProjectTypeListDataResult.

    Variables are only populated by the server, and will be ignored when sending a request.

    :param code:
    :type code: int
    :param status:
    :type status: str
    :ivar data:
    :vartype data: list[~teamcloud.models.ProjectType]
    :param location:
    :type location: str
    """

    _validation = {
        'data': {'readonly': True},
    }

    _attribute_map = {
        'code': {'key': 'code', 'type': 'int'},
        'status': {'key': 'status', 'type': 'str'},
        'data': {'key': 'data', 'type': '[ProjectType]'},
        'location': {'key': 'location', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        code: Optional[int] = None,
        status: Optional[str] = None,
        location: Optional[str] = None,
        **kwargs
    ):
        super(ProjectTypeListDataResult, self).__init__(**kwargs)
        self.code = code
        self.status = status
        self.data = None
        self.location = location


class Provider(msrest.serialization.Model):
    """Provider.

    All required parameters must be populated in order to send to Azure.

    :param id: Required.
    :type id: str
    :param url: Required.
    :type url: str
    :param auth_code: Required.
    :type auth_code: str
    :param principal_id:
    :type principal_id: str
    :param version:
    :type version: str
    :param resource_group:
    :type resource_group: ~teamcloud.models.AzureResourceGroup
    :param events:
    :type events: list[str]
    :param event_subscriptions:
    :type event_subscriptions: list[~teamcloud.models.ProviderEventSubscription]
    :param properties: Dictionary of :code:`<string>`.
    :type properties: dict[str, str]
    :param registered:
    :type registered: ~datetime.datetime
    :param type: Required.  Possible values include: "Standard", "Service", "Virtual".
    :type type: str or ~teamcloud.models.ProviderType
    :param command_mode: Required.  Possible values include: "Simple", "Extended".
    :type command_mode: str or ~teamcloud.models.ProviderCommandMode
    """

    _validation = {
        'id': {'required': True},
        'url': {'required': True},
        'auth_code': {'required': True},
        'type': {'required': True},
        'command_mode': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'url': {'key': 'url', 'type': 'str'},
        'auth_code': {'key': 'authCode', 'type': 'str'},
        'principal_id': {'key': 'principalId', 'type': 'str'},
        'version': {'key': 'version', 'type': 'str'},
        'resource_group': {'key': 'resourceGroup', 'type': 'AzureResourceGroup'},
        'events': {'key': 'events', 'type': '[str]'},
        'event_subscriptions': {'key': 'eventSubscriptions', 'type': '[ProviderEventSubscription]'},
        'properties': {'key': 'properties', 'type': '{str}'},
        'registered': {'key': 'registered', 'type': 'iso-8601'},
        'type': {'key': 'type', 'type': 'str'},
        'command_mode': {'key': 'commandMode', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        id: str,
        url: str,
        auth_code: str,
        type: Union[str, "ProviderType"],
        command_mode: Union[str, "ProviderCommandMode"],
        principal_id: Optional[str] = None,
        version: Optional[str] = None,
        resource_group: Optional["AzureResourceGroup"] = None,
        events: Optional[List[str]] = None,
        event_subscriptions: Optional[List["ProviderEventSubscription"]] = None,
        properties: Optional[Dict[str, str]] = None,
        registered: Optional[datetime.datetime] = None,
        **kwargs
    ):
        super(Provider, self).__init__(**kwargs)
        self.id = id
        self.url = url
        self.auth_code = auth_code
        self.principal_id = principal_id
        self.version = version
        self.resource_group = resource_group
        self.events = events
        self.event_subscriptions = event_subscriptions
        self.properties = properties
        self.registered = registered
        self.type = type
        self.command_mode = command_mode


class ProviderData(msrest.serialization.Model):
    """ProviderData.

    Variables are only populated by the server, and will be ignored when sending a request.

    All required parameters must be populated in order to send to Azure.

    :param id: Required.
    :type id: str
    :param name:
    :type name: str
    :param location:
    :type location: str
    :param is_secret:
    :type is_secret: bool
    :param is_shared:
    :type is_shared: bool
    :param scope: Required.  Possible values include: "System", "Project".
    :type scope: str or ~teamcloud.models.ProviderDataScope
    :param data_type: Required.  Possible values include: "Property", "Service".
    :type data_type: str or ~teamcloud.models.ProviderDataType
    :ivar string_value:
    :vartype string_value: str
    """

    _validation = {
        'id': {'required': True},
        'scope': {'required': True},
        'data_type': {'required': True},
        'string_value': {'readonly': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'location': {'key': 'location', 'type': 'str'},
        'is_secret': {'key': 'isSecret', 'type': 'bool'},
        'is_shared': {'key': 'isShared', 'type': 'bool'},
        'scope': {'key': 'scope', 'type': 'str'},
        'data_type': {'key': 'dataType', 'type': 'str'},
        'string_value': {'key': 'stringValue', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        id: str,
        scope: Union[str, "ProviderDataScope"],
        data_type: Union[str, "ProviderDataType"],
        name: Optional[str] = None,
        location: Optional[str] = None,
        is_secret: Optional[bool] = None,
        is_shared: Optional[bool] = None,
        **kwargs
    ):
        super(ProviderData, self).__init__(**kwargs)
        self.id = id
        self.name = name
        self.location = location
        self.is_secret = is_secret
        self.is_shared = is_shared
        self.scope = scope
        self.data_type = data_type
        self.string_value = None


class ProviderDataListDataResult(msrest.serialization.Model):
    """ProviderDataListDataResult.

    Variables are only populated by the server, and will be ignored when sending a request.

    :param code:
    :type code: int
    :param status:
    :type status: str
    :ivar data:
    :vartype data: list[~teamcloud.models.ProviderData]
    :param location:
    :type location: str
    """

    _validation = {
        'data': {'readonly': True},
    }

    _attribute_map = {
        'code': {'key': 'code', 'type': 'int'},
        'status': {'key': 'status', 'type': 'str'},
        'data': {'key': 'data', 'type': '[ProviderData]'},
        'location': {'key': 'location', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        code: Optional[int] = None,
        status: Optional[str] = None,
        location: Optional[str] = None,
        **kwargs
    ):
        super(ProviderDataListDataResult, self).__init__(**kwargs)
        self.code = code
        self.status = status
        self.data = None
        self.location = location


class ProviderDataResult(msrest.serialization.Model):
    """ProviderDataResult.

    :param code:
    :type code: int
    :param status:
    :type status: str
    :param data:
    :type data: ~teamcloud.models.Provider
    :param location:
    :type location: str
    """

    _attribute_map = {
        'code': {'key': 'code', 'type': 'int'},
        'status': {'key': 'status', 'type': 'str'},
        'data': {'key': 'data', 'type': 'Provider'},
        'location': {'key': 'location', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        code: Optional[int] = None,
        status: Optional[str] = None,
        data: Optional["Provider"] = None,
        location: Optional[str] = None,
        **kwargs
    ):
        super(ProviderDataResult, self).__init__(**kwargs)
        self.code = code
        self.status = status
        self.data = data
        self.location = location


class ProviderDataReturnResult(msrest.serialization.Model):
    """ProviderDataReturnResult.

    :param code:
    :type code: int
    :param status:
    :type status: str
    :param data:
    :type data: ~teamcloud.models.ProviderData
    :param location:
    :type location: str
    """

    _attribute_map = {
        'code': {'key': 'code', 'type': 'int'},
        'status': {'key': 'status', 'type': 'str'},
        'data': {'key': 'data', 'type': 'ProviderData'},
        'location': {'key': 'location', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        code: Optional[int] = None,
        status: Optional[str] = None,
        data: Optional["ProviderData"] = None,
        location: Optional[str] = None,
        **kwargs
    ):
        super(ProviderDataReturnResult, self).__init__(**kwargs)
        self.code = code
        self.status = status
        self.data = data
        self.location = location


class ProviderEventSubscription(msrest.serialization.Model):
    """ProviderEventSubscription.

    :param event_type:
    :type event_type: str
    """

    _attribute_map = {
        'event_type': {'key': 'eventType', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        event_type: Optional[str] = None,
        **kwargs
    ):
        super(ProviderEventSubscription, self).__init__(**kwargs)
        self.event_type = event_type


class ProviderListDataResult(msrest.serialization.Model):
    """ProviderListDataResult.

    Variables are only populated by the server, and will be ignored when sending a request.

    :param code:
    :type code: int
    :param status:
    :type status: str
    :ivar data:
    :vartype data: list[~teamcloud.models.Provider]
    :param location:
    :type location: str
    """

    _validation = {
        'data': {'readonly': True},
    }

    _attribute_map = {
        'code': {'key': 'code', 'type': 'int'},
        'status': {'key': 'status', 'type': 'str'},
        'data': {'key': 'data', 'type': '[Provider]'},
        'location': {'key': 'location', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        code: Optional[int] = None,
        status: Optional[str] = None,
        location: Optional[str] = None,
        **kwargs
    ):
        super(ProviderListDataResult, self).__init__(**kwargs)
        self.code = code
        self.status = status
        self.data = None
        self.location = location


class ProviderReference(msrest.serialization.Model):
    """ProviderReference.

    All required parameters must be populated in order to send to Azure.

    :param id: Required.
    :type id: str
    :param depends_on:
    :type depends_on: list[str]
    :param properties: Dictionary of :code:`<string>`.
    :type properties: dict[str, str]
    :param metadata: Dictionary of :code:`<any>`.
    :type metadata: dict[str, object]
    """

    _validation = {
        'id': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'depends_on': {'key': 'dependsOn', 'type': '[str]'},
        'properties': {'key': 'properties', 'type': '{str}'},
        'metadata': {'key': 'metadata', 'type': '{object}'},
    }

    def __init__(
        self,
        *,
        id: str,
        depends_on: Optional[List[str]] = None,
        properties: Optional[Dict[str, str]] = None,
        metadata: Optional[Dict[str, object]] = None,
        **kwargs
    ):
        super(ProviderReference, self).__init__(**kwargs)
        self.id = id
        self.depends_on = depends_on
        self.properties = properties
        self.metadata = metadata


class ReferenceLink(msrest.serialization.Model):
    """ReferenceLink.

    Variables are only populated by the server, and will be ignored when sending a request.

    :param href:
    :type href: str
    :ivar templated:
    :vartype templated: bool
    """

    _validation = {
        'templated': {'readonly': True},
    }

    _attribute_map = {
        'href': {'key': 'href', 'type': 'str'},
        'templated': {'key': 'templated', 'type': 'bool'},
    }

    def __init__(
        self,
        *,
        href: Optional[str] = None,
        **kwargs
    ):
        super(ReferenceLink, self).__init__(**kwargs)
        self.href = href
        self.templated = None


class ResultError(msrest.serialization.Model):
    """ResultError.

    :param code:  Possible values include: "Unknown", "Failed", "Conflict", "NotFound",
     "ServerError", "ValidationError", "Unauthorized", "Forbidden".
    :type code: str or ~teamcloud.models.ResultErrorCode
    :param message:
    :type message: str
    :param errors:
    :type errors: list[~teamcloud.models.ValidationError]
    """

    _attribute_map = {
        'code': {'key': 'code', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
        'errors': {'key': 'errors', 'type': '[ValidationError]'},
    }

    def __init__(
        self,
        *,
        code: Optional[Union[str, "ResultErrorCode"]] = None,
        message: Optional[str] = None,
        errors: Optional[List["ValidationError"]] = None,
        **kwargs
    ):
        super(ResultError, self).__init__(**kwargs)
        self.code = code
        self.message = message
        self.errors = errors


class StatusResult(msrest.serialization.Model):
    """StatusResult.

    Variables are only populated by the server, and will be ignored when sending a request.

    :param code:
    :type code: int
    :param status:
    :type status: str
    :ivar state:
    :vartype state: str
    :param state_message:
    :type state_message: str
    :param location:
    :type location: str
    :param errors:
    :type errors: list[~teamcloud.models.ResultError]
    :param tracking_id:
    :type tracking_id: str
    """

    _validation = {
        'state': {'readonly': True},
    }

    _attribute_map = {
        'code': {'key': 'code', 'type': 'int'},
        'status': {'key': 'status', 'type': 'str'},
        'state': {'key': 'state', 'type': 'str'},
        'state_message': {'key': 'stateMessage', 'type': 'str'},
        'location': {'key': 'location', 'type': 'str'},
        'errors': {'key': 'errors', 'type': '[ResultError]'},
        'tracking_id': {'key': '_trackingId', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        code: Optional[int] = None,
        status: Optional[str] = None,
        state_message: Optional[str] = None,
        location: Optional[str] = None,
        errors: Optional[List["ResultError"]] = None,
        tracking_id: Optional[str] = None,
        **kwargs
    ):
        super(StatusResult, self).__init__(**kwargs)
        self.code = code
        self.status = status
        self.state = None
        self.state_message = state_message
        self.location = location
        self.errors = errors
        self.tracking_id = tracking_id


class StringDictionaryDataResult(msrest.serialization.Model):
    """StringDictionaryDataResult.

    Variables are only populated by the server, and will be ignored when sending a request.

    :param code:
    :type code: int
    :param status:
    :type status: str
    :ivar data: Dictionary of :code:`<string>`.
    :vartype data: dict[str, str]
    :param location:
    :type location: str
    """

    _validation = {
        'data': {'readonly': True},
    }

    _attribute_map = {
        'code': {'key': 'code', 'type': 'int'},
        'status': {'key': 'status', 'type': 'str'},
        'data': {'key': 'data', 'type': '{str}'},
        'location': {'key': 'location', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        code: Optional[int] = None,
        status: Optional[str] = None,
        location: Optional[str] = None,
        **kwargs
    ):
        super(StringDictionaryDataResult, self).__init__(**kwargs)
        self.code = code
        self.status = status
        self.data = None
        self.location = location


class TeamCloudApplication(msrest.serialization.Model):
    """TeamCloudApplication.

    Variables are only populated by the server, and will be ignored when sending a request.

    :param url:
    :type url: str
    :param version:
    :type version: str
    :ivar type:  Default value: "Web".
    :vartype type: str
    :param resource_group:
    :type resource_group: ~teamcloud.models.AzureResourceGroup
    """

    _validation = {
        'type': {'constant': True},
    }

    _attribute_map = {
        'url': {'key': 'url', 'type': 'str'},
        'version': {'key': 'version', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'resource_group': {'key': 'resourceGroup', 'type': 'AzureResourceGroup'},
    }

    type = "Web"

    def __init__(
        self,
        *,
        url: Optional[str] = None,
        version: Optional[str] = None,
        resource_group: Optional["AzureResourceGroup"] = None,
        **kwargs
    ):
        super(TeamCloudApplication, self).__init__(**kwargs)
        self.url = url
        self.version = version
        self.resource_group = resource_group


class TeamCloudInstance(msrest.serialization.Model):
    """TeamCloudInstance.

    :param version:
    :type version: str
    :param resource_group:
    :type resource_group: ~teamcloud.models.AzureResourceGroup
    :param tags: A set of tags. Dictionary of :code:`<string>`.
    :type tags: dict[str, str]
    :param applications:
    :type applications: list[~teamcloud.models.TeamCloudApplication]
    """

    _attribute_map = {
        'version': {'key': 'version', 'type': 'str'},
        'resource_group': {'key': 'resourceGroup', 'type': 'AzureResourceGroup'},
        'tags': {'key': 'tags', 'type': '{str}'},
        'applications': {'key': 'applications', 'type': '[TeamCloudApplication]'},
    }

    def __init__(
        self,
        *,
        version: Optional[str] = None,
        resource_group: Optional["AzureResourceGroup"] = None,
        tags: Optional[Dict[str, str]] = None,
        applications: Optional[List["TeamCloudApplication"]] = None,
        **kwargs
    ):
        super(TeamCloudInstance, self).__init__(**kwargs)
        self.version = version
        self.resource_group = resource_group
        self.tags = tags
        self.applications = applications


class TeamCloudInstanceDataResult(msrest.serialization.Model):
    """TeamCloudInstanceDataResult.

    :param code:
    :type code: int
    :param status:
    :type status: str
    :param data:
    :type data: ~teamcloud.models.TeamCloudInstance
    :param location:
    :type location: str
    """

    _attribute_map = {
        'code': {'key': 'code', 'type': 'int'},
        'status': {'key': 'status', 'type': 'str'},
        'data': {'key': 'data', 'type': 'TeamCloudInstance'},
        'location': {'key': 'location', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        code: Optional[int] = None,
        status: Optional[str] = None,
        data: Optional["TeamCloudInstance"] = None,
        location: Optional[str] = None,
        **kwargs
    ):
        super(TeamCloudInstanceDataResult, self).__init__(**kwargs)
        self.code = code
        self.status = status
        self.data = data
        self.location = location


class User(msrest.serialization.Model):
    """User.

    All required parameters must be populated in order to send to Azure.

    :param id: Required.
    :type id: str
    :param user_type: Required.  Possible values include: "User", "System", "Provider",
     "Application".
    :type user_type: str or ~teamcloud.models.UserType
    :param role: Required.  Possible values include: "None", "Provider", "Creator", "Admin".
    :type role: str or ~teamcloud.models.UserRole
    :param project_memberships:
    :type project_memberships: list[~teamcloud.models.ProjectMembership]
    :param properties: Dictionary of :code:`<string>`.
    :type properties: dict[str, str]
    """

    _validation = {
        'id': {'required': True},
        'user_type': {'required': True},
        'role': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'user_type': {'key': 'userType', 'type': 'str'},
        'role': {'key': 'role', 'type': 'str'},
        'project_memberships': {'key': 'projectMemberships', 'type': '[ProjectMembership]'},
        'properties': {'key': 'properties', 'type': '{str}'},
    }

    def __init__(
        self,
        *,
        id: str,
        user_type: Union[str, "UserType"],
        role: Union[str, "UserRole"],
        project_memberships: Optional[List["ProjectMembership"]] = None,
        properties: Optional[Dict[str, str]] = None,
        **kwargs
    ):
        super(User, self).__init__(**kwargs)
        self.id = id
        self.user_type = user_type
        self.role = role
        self.project_memberships = project_memberships
        self.properties = properties


class UserDataResult(msrest.serialization.Model):
    """UserDataResult.

    :param code:
    :type code: int
    :param status:
    :type status: str
    :param data:
    :type data: ~teamcloud.models.User
    :param location:
    :type location: str
    """

    _attribute_map = {
        'code': {'key': 'code', 'type': 'int'},
        'status': {'key': 'status', 'type': 'str'},
        'data': {'key': 'data', 'type': 'User'},
        'location': {'key': 'location', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        code: Optional[int] = None,
        status: Optional[str] = None,
        data: Optional["User"] = None,
        location: Optional[str] = None,
        **kwargs
    ):
        super(UserDataResult, self).__init__(**kwargs)
        self.code = code
        self.status = status
        self.data = data
        self.location = location


class UserDefinition(msrest.serialization.Model):
    """UserDefinition.

    :param identifier:
    :type identifier: str
    :param role:
    :type role: str
    :param properties: Dictionary of :code:`<string>`.
    :type properties: dict[str, str]
    """

    _attribute_map = {
        'identifier': {'key': 'identifier', 'type': 'str'},
        'role': {'key': 'role', 'type': 'str'},
        'properties': {'key': 'properties', 'type': '{str}'},
    }

    def __init__(
        self,
        *,
        identifier: Optional[str] = None,
        role: Optional[str] = None,
        properties: Optional[Dict[str, str]] = None,
        **kwargs
    ):
        super(UserDefinition, self).__init__(**kwargs)
        self.identifier = identifier
        self.role = role
        self.properties = properties


class UserListDataResult(msrest.serialization.Model):
    """UserListDataResult.

    Variables are only populated by the server, and will be ignored when sending a request.

    :param code:
    :type code: int
    :param status:
    :type status: str
    :ivar data:
    :vartype data: list[~teamcloud.models.User]
    :param location:
    :type location: str
    """

    _validation = {
        'data': {'readonly': True},
    }

    _attribute_map = {
        'code': {'key': 'code', 'type': 'int'},
        'status': {'key': 'status', 'type': 'str'},
        'data': {'key': 'data', 'type': '[User]'},
        'location': {'key': 'location', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        code: Optional[int] = None,
        status: Optional[str] = None,
        location: Optional[str] = None,
        **kwargs
    ):
        super(UserListDataResult, self).__init__(**kwargs)
        self.code = code
        self.status = status
        self.data = None
        self.location = location


class ValidationError(msrest.serialization.Model):
    """ValidationError.

    :param field:
    :type field: str
    :param message:
    :type message: str
    """

    _attribute_map = {
        'field': {'key': 'field', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
    }

    def __init__(
        self,
        *,
        field: Optional[str] = None,
        message: Optional[str] = None,
        **kwargs
    ):
        super(ValidationError, self).__init__(**kwargs)
        self.field = field
        self.message = message
