# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ProjectLinks(Model):
    """ProjectLinks.

    :param _self:
    :type _self: ~teamcloud.models.ReferenceLink
    :param identity:
    :type identity: ~teamcloud.models.ReferenceLink
    :param users:
    :type users: ~teamcloud.models.ReferenceLink
    """

    _attribute_map = {
        '_self': {'key': '_self', 'type': 'ReferenceLink'},
        'identity': {'key': 'identity', 'type': 'ReferenceLink'},
        'users': {'key': 'users', 'type': 'ReferenceLink'},
    }

    def __init__(self, *, _self=None, identity=None, users=None, **kwargs) -> None:
        super(ProjectLinks, self).__init__(**kwargs)
        self._self = _self
        self.identity = identity
        self.users = users
