# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class User(Model):
    """User.

    :param id:
    :type id: str
    :param user_type: Possible values include: 'User', 'System', 'Provider',
     'Application'
    :type user_type: str or ~teamcloud.models.enum
    :param role: Possible values include: 'None', 'Provider', 'Creator',
     'Admin'
    :type role: str or ~teamcloud.models.enum
    :param project_memberships:
    :type project_memberships: list[~teamcloud.models.ProjectMembership]
    :param properties:
    :type properties: dict[str, str]
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'user_type': {'key': 'userType', 'type': 'str'},
        'role': {'key': 'role', 'type': 'str'},
        'project_memberships': {'key': 'projectMemberships', 'type': '[ProjectMembership]'},
        'properties': {'key': 'properties', 'type': '{str}'},
    }

    def __init__(self, *, id: str=None, user_type=None, role=None, project_memberships=None, properties=None, **kwargs) -> None:
        super(User, self).__init__(**kwargs)
        self.id = id
        self.user_type = user_type
        self.role = role
        self.project_memberships = project_memberships
        self.properties = properties
